CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  DECLARE ofset INT;
  SET ofset = N-1;
  RETURN (
    SELECT DISTINCT SALARY FROM EMPLOYEE 
    ORDER BY SALARY DESC 
    LIMIT 1 OFFSET ofset

  );
END